// <auto-generated />
using CadastroGeral.Connection;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace CadastroGeral.Migrations
{
    [DbContext(typeof(BancoContext)), Migration("20220727145131_CriacaoTabelaUsuarios")]
    internal class CriacaoTabelaUsuariosBase
    {
    }
}